[platformio]
default_envs = esp32-c6-supermini

[env:esp32-c6-supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
extra_scripts = pre:scripts/embed_web.py
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D MORSE_OUTPUT_PIN=0
